spring.application.name=ridehub-api
server.port=8081

# MongoDB config
spring.data.mongodb.uri=mongodb://localhost:27017/ridehub_database

# Logging
logging.level.org.springframework.security=INFO

# JWT secret
app.jwt.secret=ridehub_secure_jwt_key_2025_production_secret_key_must_be_long
app.jwt.expiration-ms=3600000
